name: 'Check semantic version'
description: 'Check the version of your package is the same as the semantic version calculated from the Conventional Commits on the branch.'
author: 'Marcus Lugg'
branding:
  icon: git-commit
  color: green
inputs:
  path:
    description: 'The path of the file containing the current version number (must be one of "setup.py", "pyproject.toml", or "package.json").'
    required: true
  breaking_change_indicated_by:
    description: 'The semantic version number type that a breaking change increments (must be one of "major", "minor", or "patch").'
    required: false
    default: 'major'
runs:
   using: 'docker'
   image: 'docker://octue/check-semantic-version:1.0.0.beta-3'
   args:
     - ${{ inputs.path }}
     - ${{ inputs.breaking_change_indicated_by }}
